import type { Project, User } from "./types"

export const seedUsers: User[] = [
  {
    id: "user-1",
    name: "John Doe",
    email: "john@example.com",
    role: "owner",
  },
  {
    id: "user-2",
    name: "Jane Smith",
    email: "jane@example.com",
    role: "admin",
  },
  {
    id: "user-3",
    name: "Bob Johnson",
    email: "bob@example.com",
    role: "member",
  },
  {
    id: "user-4",
    name: "Alice Williams",
    email: "alice@example.com",
    role: "viewer",
  },
]

export const seedProject: Omit<Project, "id" | "createdAt" | "updatedAt"> = {
  title: "Product Launch",
  description: "Q1 2025 Product Launch Planning",
  boards: [
    {
      id: "board-1",
      title: "Development Sprint",
      description: "Current development tasks",
      projectId: "",
      lists: [
        {
          id: "list-1",
          title: "To Do",
          boardId: "board-1",
          position: 0,
          cards: [
            {
              id: "card-1",
              title: "Design new landing page",
              description: "Create mockups for the new product landing page",
              listId: "list-1",
              position: 0,
              priority: "high",
              dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
              assignedTo: ["user-2"],
              labels: ["label-1"],
              comments: [],
              createdAt: new Date(),
              updatedAt: new Date(),
              createdBy: "user-1",
            },
            {
              id: "card-2",
              title: "Set up CI/CD pipeline",
              description: "Configure automated testing and deployment",
              listId: "list-1",
              position: 1,
              priority: "medium",
              assignedTo: ["user-3"],
              labels: ["label-2"],
              comments: [],
              createdAt: new Date(),
              updatedAt: new Date(),
              createdBy: "user-1",
            },
          ],
        },
        {
          id: "list-2",
          title: "In Progress",
          boardId: "board-1",
          position: 1,
          cards: [
            {
              id: "card-3",
              title: "Implement user authentication",
              description: "Add OAuth and email/password authentication",
              listId: "list-2",
              position: 0,
              priority: "urgent",
              dueDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
              assignedTo: ["user-3"],
              labels: ["label-2", "label-3"],
              comments: [
                {
                  id: "comment-1",
                  content: "Started working on OAuth integration",
                  userId: "user-3",
                  createdAt: new Date(),
                  updatedAt: new Date(),
                },
              ],
              createdAt: new Date(),
              updatedAt: new Date(),
              createdBy: "user-1",
            },
          ],
        },
        {
          id: "list-3",
          title: "Review",
          boardId: "board-1",
          position: 2,
          cards: [
            {
              id: "card-4",
              title: "Update documentation",
              description: "Review and update API documentation",
              listId: "list-3",
              position: 0,
              priority: "low",
              assignedTo: ["user-2"],
              labels: ["label-4"],
              comments: [],
              createdAt: new Date(),
              updatedAt: new Date(),
              createdBy: "user-2",
            },
          ],
        },
        {
          id: "list-4",
          title: "Done",
          boardId: "board-1",
          position: 3,
          cards: [
            {
              id: "card-5",
              title: "Set up project repository",
              description: "Initialize Git repository and project structure",
              listId: "list-4",
              position: 0,
              priority: "high",
              assignedTo: ["user-1"],
              labels: ["label-2"],
              comments: [],
              createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
              updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
              createdBy: "user-1",
            },
          ],
        },
      ],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ],
  members: seedUsers,
  labels: [
    { id: "label-1", name: "Design", color: "#8b5cf6" },
    { id: "label-2", name: "Development", color: "#3b82f6" },
    { id: "label-3", name: "Bug", color: "#ef4444" },
    { id: "label-4", name: "Documentation", color: "#10b981" },
  ],
}
